version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Check repo for new code.

      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - run:
          name: show env and install git
          command: |
		    apt update \
		    apt -y install ssh \
		    #ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_8685bc80cca791e62cbd511728584c05 root@95.65.17.14 -p 20009 'cd /data; git clone https://github.com/'$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME'.git '$CIRCLE_PROJECT_REPONAME'-'$CIRCLE_BUILD_NUM'; cd '$CIRCLE_PROJECT_REPONAME'-'$CIRCLE_BUILD_NUM'; ./rebuild '$CIRCLE_PROJECT_REPONAME' '$CIRCLE_PROJECT_USERNAME' '$CIRCLE_BUILD_NUM' '$CIRCLE_PREVIOUS_BUILD_NUM

