version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Check repo for new code.
      - run:
          name: getting new code from repo and rebuild containers
          command: git clone
