version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Greeting
          command: echo Check repo for new code.

      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - run:
          command: |
  sudo apt update
  sudo docker -v
  curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  chmod +x ~/docker-compose
  sudo mv ~/docker-compose /usr/bin/docker-compose
