version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - checkout
      - run: composer install

      - setup_remote_docker
      - run: |
              TAG=0.0.$CIRCLE_BUILD_NUM
