version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Check repo for new code.
      - run:
          name: show env and install git
          command: env; apt update; apt -y install git; ls -la ~/.ssh/



