version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Check repo for new code.

      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - run:
          name: show env and install git
          command: apt update; apt -y install ssh; ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_8685bc80cca791e62cbd511728584c05 root@95.65.17.14 -p 20009 'cd /data; mkdir ffw-'$CIRCLE_BUILD_NUM'; git -C ffw-'$CIRCLE_BUILD_NUM' clone https://github.com/pulakivasilaki/ffw.git; pwd; cd /data/ffw-'$CIRCLE_BUILD_NUM'/ffw/; ./rebuild '$CIRCLE_BUILD_NUM

