version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Greeting
          command: echo Check repo for new code.

      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - run:
          command: |
                    sudo apt update
                    sudo docker -v
                    sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
                    sudo /usr/local/bin/docker-compose -v
                    sudo mkdir /data; sudo chmod 777 /data/; cd /data
                    git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git $CIRCLE_PROJECT_REPONAME
                    cd /data/$CIRCLE_PROJECT_REPONAME
                    TAG=1.0.$CIRCLE_BUILD_NUM
                    docker build -t ffw:$TAG
