version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    steps:
      - checkout
      - run: git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git $CIRCLE_PROJECT_REPONAME
      - run: pwd; ls -la
      - setup_remote_docker
      - run:
          name: Greeting
          command: echo Check repo for new code.
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - run:
          command: |
                    sudo apt update
                    docker -v
