version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    steps:
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "86:85:bc:80:cc:a7:91:e6:2c:bd:51:17:28:58:4c:05"

      - checkout
      - run: git clone $CIRCLE_REPOSITORY_URL $CIRCLE_PROJECT_REPONAME
      - run: sudo apt update
      - run: sudo apt -y install php rsync
      - run: php -r "readfile('http://getcomposer.org/installer');" | php -- --filename=composer
      - run: chmod +x composer
      - run: ./composer install
      - run: sudo cp -r . /var/www/html/
      - run: ls -la $PWD
      - setup_remote_docker
      - run:
          command: |
                    set -x
                    TAG=1.0.$CIRCLE_BUILD_NUM
                    docker build -t pulakivasilaki/ffw:$TAG .
                    docker login -u $docker_user -p $docker_pass
                    docker push pulakivasilaki/ffw:$TAG
